version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.3-browsers
      - image: circleci/mysql:5.7
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_USER: root
          MYSQL_ROOT_PASSWORD: ''
          MYSQL_DATABASE: laravel_circleci

    working_directory: ~/laravel

    steps:
      - checkout
      - run:
          name: Install PHP exts
          command: |
            sudo apt-get update
            sudo docker-php-ext-install zip
            sudo docker-php-ext-install pdo_mysql
            sudo apt-get install -y git curl libmcrypt-dev default-mysql-client

      - run: sudo composer self-update

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "composer.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: composer install -n --prefer-dist

      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}

      # prepare the database
      - run:
          name: Create Environment file and generate app key
          command: |
            mv .env.testing .env
            php artisan key:generate

      - run:
          name: Setup Laravel stuffs
          command: |
            php artisan migrate --force

      - run:
          name: "Generate Passport encryption keys"
          command: php artisan passport:install

      - run:
          name: "Run Tests"
          command: ./vendor/bin/phpunit
